substitutions:
  _REGION: asia-south1
  _REPOSITORY: shoposphere
  _TAG: latest

steps:
  - name: gcr.io/cloud-builders/docker
    id: build-auth
    args:
      - build
      - -f
      - apps/auth-service/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/auth-service:${_TAG}
      - .

  - name: gcr.io/cloud-builders/docker
    id: build-tenant
    args:
      - build
      - -f
      - apps/tenant-service/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/tenant-service:${_TAG}
      - .

  - name: gcr.io/cloud-builders/docker
    id: build-core
    args:
      - build
      - -f
      - apps/core-api/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/core-api:${_TAG}
      - .

  - name: gcr.io/cloud-builders/docker
    id: build-orders
    args:
      - build
      - -f
      - apps/order-service/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/order-service:${_TAG}
      - .

  - name: gcr.io/cloud-builders/docker
    id: build-reports
    args:
      - build
      - -f
      - apps/report-service/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/report-service:${_TAG}
      - .

  - name: gcr.io/cloud-builders/docker
    id: build-frontend
    args:
      - build
      - -f
      - frontend/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:${_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/auth-service:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/tenant-service:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/core-api:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/order-service:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/report-service:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:${_TAG}
